services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    plan: free

  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main
    plan: free
